package model.entity;
// Generated Dec 25, 2014 2:34:01 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Exams generated by hbm2java
 */
public class Exams  implements java.io.Serializable {


     private int examsId;
     private Quiz quiz;
     private User user;
     private Float points;
     private Set examsDetailses = new HashSet(0);

    public Exams() {
    }

	
    public Exams(int examsId) {
        this.examsId = examsId;
    }
    public Exams(int examsId, Quiz quiz, User user, Float points, Set examsDetailses) {
       this.examsId = examsId;
       this.quiz = quiz;
       this.user = user;
       this.points = points;
       this.examsDetailses = examsDetailses;
    }
   
    public int getExamsId() {
        return this.examsId;
    }
    
    public void setExamsId(int examsId) {
        this.examsId = examsId;
    }
    public Quiz getQuiz() {
        return this.quiz;
    }
    
    public void setQuiz(Quiz quiz) {
        this.quiz = quiz;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Float getPoints() {
        return this.points;
    }
    
    public void setPoints(Float points) {
        this.points = points;
    }
    public Set getExamsDetailses() {
        return this.examsDetailses;
    }
    
    public void setExamsDetailses(Set examsDetailses) {
        this.examsDetailses = examsDetailses;
    }




}


