package model.entity;
// Generated Dec 25, 2014 2:34:01 AM by Hibernate Tools 3.6.0



/**
 * ExamsDetails generated by hbm2java
 */
public class ExamsDetails  implements java.io.Serializable {


     private ExamsDetailsId id;
     private Exams exams;
     private Questions questions;
     private String answer;

    public ExamsDetails() {
    }

	
    public ExamsDetails(ExamsDetailsId id, Exams exams, Questions questions) {
        this.id = id;
        this.exams = exams;
        this.questions = questions;
    }
    public ExamsDetails(ExamsDetailsId id, Exams exams, Questions questions, String answer) {
       this.id = id;
       this.exams = exams;
       this.questions = questions;
       this.answer = answer;
    }
   
    public ExamsDetailsId getId() {
        return this.id;
    }
    
    public void setId(ExamsDetailsId id) {
        this.id = id;
    }
    public Exams getExams() {
        return this.exams;
    }
    
    public void setExams(Exams exams) {
        this.exams = exams;
    }
    public Questions getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Questions questions) {
        this.questions = questions;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }




}


