package model.entity;
// Generated Dec 25, 2014 2:34:01 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Questions generated by hbm2java
 */
public class Questions  implements java.io.Serializable {


     private Integer questionsId;
     private Quiz quiz;
     private String content;
     private String chooseA;
     private String chooseB;
     private String chooseC;
     private String chooseD;
     private String answer;
     private Set examsDetailses = new HashSet(0);

    public Questions() {
    }

    public Questions(Quiz quiz, String content, String chooseA, String chooseB, String chooseC, String chooseD, String answer, Set examsDetailses) {
       this.quiz = quiz;
       this.content = content;
       this.chooseA = chooseA;
       this.chooseB = chooseB;
       this.chooseC = chooseC;
       this.chooseD = chooseD;
       this.answer = answer;
       this.examsDetailses = examsDetailses;
    }
   
    public Integer getQuestionsId() {
        return this.questionsId;
    }
    
    public void setQuestionsId(Integer questionsId) {
        this.questionsId = questionsId;
    }
    public Quiz getQuiz() {
        return this.quiz;
    }
    
    public void setQuiz(Quiz quiz) {
        this.quiz = quiz;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getChooseA() {
        return this.chooseA;
    }
    
    public void setChooseA(String chooseA) {
        this.chooseA = chooseA;
    }
    public String getChooseB() {
        return this.chooseB;
    }
    
    public void setChooseB(String chooseB) {
        this.chooseB = chooseB;
    }
    public String getChooseC() {
        return this.chooseC;
    }
    
    public void setChooseC(String chooseC) {
        this.chooseC = chooseC;
    }
    public String getChooseD() {
        return this.chooseD;
    }
    
    public void setChooseD(String chooseD) {
        this.chooseD = chooseD;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }
    public Set getExamsDetailses() {
        return this.examsDetailses;
    }
    
    public void setExamsDetailses(Set examsDetailses) {
        this.examsDetailses = examsDetailses;
    }




}


