package model.entity;
// Generated Dec 25, 2014 2:34:01 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Quiz generated by hbm2java
 */
public class Quiz  implements java.io.Serializable {


     private int quizId;
     private Disciplines disciplines;
     private String content;
     private Boolean active;
     private Boolean isview;
     private int time;
     private int totalques;
     private Set examses = new HashSet(0);
     private Set questionses = new HashSet(0);

    public Quiz() {
    }

	
    public Quiz(int quizId) {
        this.quizId = quizId;
    }

    public Quiz( Disciplines disciplines, String content, Boolean active, Boolean isview, int time, int totalques) {
        this.disciplines = disciplines;
        this.content = content;
        this.active = active;
        this.isview = isview;
        this.time = time;
        this.totalques = totalques;
    }
    
   
    public int getQuizId() {
        return this.quizId;
    }
    
    public void setQuizId(int quizId) {
        this.quizId = quizId;
    }
    public Disciplines getDisciplines() {
        return this.disciplines;
    }
    
    public void setDisciplines(Disciplines disciplines) {
        this.disciplines = disciplines;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public Boolean getIsview() {
        return this.isview;
    }
    
    public void setIsview(Boolean isview) {
        this.isview = isview;
    }

    public int getTime() {
        return time;
    }

    public void setTime(int time) {
        this.time = time;
    }

    public int getTotalques() {
        return totalques;
    }

    public void setTotalques(int totalques) {
        this.totalques = totalques;
    }
    
    public Set getExamses() {
        return this.examses;
    }
    
    public void setExamses(Set examses) {
        this.examses = examses;
    }
    public Set getQuestionses() {
        return this.questionses;
    }
    
    public void setQuestionses(Set questionses) {
        this.questionses = questionses;
    }




}


