package Controller.filter;
// Generated Dec 23, 2014 7:47:50 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Clss generated by hbm2java
 */
public class Clss  implements java.io.Serializable {


     private Integer clssId;
     private String clssname;
     private Integer yearStart;
     private Integer yearfinish;
     private String notes;
     private Boolean actived;
     private Set users = new HashSet(0);

    public Clss() {
    }

    public Clss(String clssname, Integer yearStart, Integer yearfinish, String notes, Boolean actived, Set users) {
       this.clssname = clssname;
       this.yearStart = yearStart;
       this.yearfinish = yearfinish;
       this.notes = notes;
       this.actived = actived;
       this.users = users;
    }
   
    public Integer getClssId() {
        return this.clssId;
    }
    
    public void setClssId(Integer clssId) {
        this.clssId = clssId;
    }
    public String getClssname() {
        return this.clssname;
    }
    
    public void setClssname(String clssname) {
        this.clssname = clssname;
    }
    public Integer getYearStart() {
        return this.yearStart;
    }
    
    public void setYearStart(Integer yearStart) {
        this.yearStart = yearStart;
    }
    public Integer getYearfinish() {
        return this.yearfinish;
    }
    
    public void setYearfinish(Integer yearfinish) {
        this.yearfinish = yearfinish;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public Boolean getActived() {
        return this.actived;
    }
    
    public void setActived(Boolean actived) {
        this.actived = actived;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


