package Controller.filter;
// Generated Dec 23, 2014 7:47:50 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Disciplines generated by hbm2java
 */
public class Disciplines  implements java.io.Serializable {


     private Integer disciplinesId;
     private String discipname;
     private Set quizs = new HashSet(0);

    public Disciplines() {
    }

    public Disciplines(String discipname, Set quizs) {
       this.discipname = discipname;
       this.quizs = quizs;
    }
   
    public Integer getDisciplinesId() {
        return this.disciplinesId;
    }
    
    public void setDisciplinesId(Integer disciplinesId) {
        this.disciplinesId = disciplinesId;
    }
    public String getDiscipname() {
        return this.discipname;
    }
    
    public void setDiscipname(String discipname) {
        this.discipname = discipname;
    }
    public Set getQuizs() {
        return this.quizs;
    }
    
    public void setQuizs(Set quizs) {
        this.quizs = quizs;
    }




}


