package Controller.filter;
// Generated Dec 23, 2014 7:47:50 PM by Hibernate Tools 3.6.0



/**
 * ExamsDetails generated by hbm2java
 */
public class ExamsDetails  implements java.io.Serializable {


     private ExamsDetailsId id;
     private Quiz quiz;
     private Exams exams;
     private String answer;

    public ExamsDetails() {
    }

	
    public ExamsDetails(ExamsDetailsId id, Quiz quiz, Exams exams) {
        this.id = id;
        this.quiz = quiz;
        this.exams = exams;
    }
    public ExamsDetails(ExamsDetailsId id, Quiz quiz, Exams exams, String answer) {
       this.id = id;
       this.quiz = quiz;
       this.exams = exams;
       this.answer = answer;
    }
   
    public ExamsDetailsId getId() {
        return this.id;
    }
    
    public void setId(ExamsDetailsId id) {
        this.id = id;
    }
    public Quiz getQuiz() {
        return this.quiz;
    }
    
    public void setQuiz(Quiz quiz) {
        this.quiz = quiz;
    }
    public Exams getExams() {
        return this.exams;
    }
    
    public void setExams(Exams exams) {
        this.exams = exams;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }




}


