package Controller.filter;
// Generated Dec 23, 2014 7:47:50 PM by Hibernate Tools 3.6.0



/**
 * ExamsDetailsId generated by hbm2java
 */
public class ExamsDetailsId  implements java.io.Serializable {


     private int examsId;
     private int quizId;

    public ExamsDetailsId() {
    }

    public ExamsDetailsId(int examsId, int quizId) {
       this.examsId = examsId;
       this.quizId = quizId;
    }
   
    public int getExamsId() {
        return this.examsId;
    }
    
    public void setExamsId(int examsId) {
        this.examsId = examsId;
    }
    public int getQuizId() {
        return this.quizId;
    }
    
    public void setQuizId(int quizId) {
        this.quizId = quizId;
    }




}


