package Controller.filter;
// Generated Dec 23, 2014 7:47:50 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Exams generated by hbm2java
 */
public class Exams  implements java.io.Serializable {


     private int examsId;
     private Integer userId;
     private Integer quizId;
     private Float points;
     private Set examsDetailses = new HashSet(0);

    public Exams() {
    }

	
    public Exams(int examsId) {
        this.examsId = examsId;
    }
    public Exams(int examsId, Integer userId, Integer quizId, Float points, Set examsDetailses) {
       this.examsId = examsId;
       this.userId = userId;
       this.quizId = quizId;
       this.points = points;
       this.examsDetailses = examsDetailses;
    }
   
    public int getExamsId() {
        return this.examsId;
    }
    
    public void setExamsId(int examsId) {
        this.examsId = examsId;
    }
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Integer getQuizId() {
        return this.quizId;
    }
    
    public void setQuizId(Integer quizId) {
        this.quizId = quizId;
    }
    public Float getPoints() {
        return this.points;
    }
    
    public void setPoints(Float points) {
        this.points = points;
    }
    public Set getExamsDetailses() {
        return this.examsDetailses;
    }
    
    public void setExamsDetailses(Set examsDetailses) {
        this.examsDetailses = examsDetailses;
    }




}


