package Controller.filter;
// Generated Dec 23, 2014 7:47:50 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private Clss clss;
     private Role role;
     private String username;
     private String password;
     private String firstname;
     private String lastname;
     private Date birthday;
     private Boolean active;

    public User() {
    }

    public User(Clss clss, Role role, String username, String password, String firstname, String lastname, Date birthday, Boolean active) {
       this.clss = clss;
       this.role = role;
       this.username = username;
       this.password = password;
       this.firstname = firstname;
       this.lastname = lastname;
       this.birthday = birthday;
       this.active = active;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Clss getClss() {
        return this.clss;
    }
    
    public void setClss(Clss clss) {
        this.clss = clss;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }




}


